sudo: false
language: node_js

node_js:
- '8'
- '6'
- '5'
- '4'

before_install:
  - git submodule update --init
  - npm install -g npm
  - npm install -g gulp typings

install:
  - npm install react react-dom
  - npm install

script:
  - npm run test:prod
  - npm run lint