sudo: false
language: node_js
node_js:
- '6'
- '5'
- '4'
before_install:
- git submodule update --init
- npm install -g npm
- npm install -g gulp
- npm install -g typings
install:
- npm install react react-dom react-addons-test-utils
- typings install
- npm install
script:
- npm run test